import type { CampaignEntry } from '../types/settings.types'

// Auto-generated from Campaign Fields.xlsx

export const PRESET_CAMPAIGNS: CampaignEntry[] = [
  {
    id: "camp-preset-in-perspective-newsletter-0",
    name: "In Perspective Newsletter",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Institutional"],
    senderPreset: {
      fromName: "Natalie Phillips",
      fromAddress: "SA.Institutional@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "marula-coral",
      subjectLine: "Subject | Ninety One In Perspective",
      previewText: "Read our latest institutional insights",
      heroImageUrl: "https://weare.ninetyone.com/l/28902/2026-03-23/9rc1bb/28902/1774251573kfgNwj5t/header_865361620_0a3323_overlay_v1_640x270.jpg",
      headline: "In Perspective",
      subHeadline: "Insights for institutional investors",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "https://pi.pardot.com/list/read/id/234003",
    },
  },
  {
    id: "camp-preset-women-and-investing-newsletter-1",
    name: "Women and Investing Newsletter",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Individual Investor"],
    senderPreset: {
      fromName: "Ninety One Women and Investing",
      fromAddress: "womenandinvesting@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "agulhas-coral",
      subjectLine: "Subject | Women and Investing",
      previewText: "",
      heroImageUrl: "https://weare.ninetyone.com/l/28902/2026-01-23/9r7qcx/28902/1769168599dmgitMJj/header_1044498000_v5_640x250.jpg",
      headline: "Women and Investing",
      subHeadline: "Helping women build financial futures fit for change",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "https://pi.pardot.com/list/read/id/187894",
    },
  },
  {
    id: "camp-preset-women-and-investing-event-2",
    name: "Women and Investing Event",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Individual Investor"],
    senderPreset: {
      fromName: "Ninety One Women and Investing",
      fromAddress: "womenandinvesting@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "agulhas-coral",
      subjectLine: "Subject | Women and Investing",
      previewText: "",
      heroImageUrl: "https://weare.ninetyone.com/l/28902/2026-01-23/9r7qcx/28902/1769168599dmgitMJj/header_1044498000_v5_640x250.jpg",
      headline: "Women and Investing",
      subHeadline: "Helping women build financial futures fit for change",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "https://pi.pardot.com/list/read/id/187894",
    },
  },
  {
    id: "camp-preset-taking-stock-newsletter-3",
    name: "Taking Stock Newsletter",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Ninety One Taking Stock",
      fromAddress: "takingstock@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "agulhas-coral",
      subjectLine: "Subject | Taking Stock \"Season\" publication",
      previewText: "Read our latest Taking Stock publication",
      heroImageUrl: "",
      headline: "",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "",
    },
  },
  {
    id: "camp-preset-taking-stock-event-4",
    name: "Taking Stock Event",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Ninety One Taking Stock",
      fromAddress: "takingstock@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "agulhas-yellowwood",
      subjectLine: "Invitation | Taking Stock | Subject",
      previewText: "Register to watch Jeremy Gardiner",
      heroImageUrl: "",
      headline: "",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "",
    },
  },
  {
    id: "camp-preset-advisor-impact-5",
    name: "Advisor Impact",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Advisor"],
    contentPreset: {
      theme: "agulhas-gold",
      subjectLine: "Subject | Advisor Impact | Month",
      previewText: "",
      heroImageUrl: "",
      headline: "Advisor Impact",
      subHeadline: "Investment Platform update",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "",
    },
  },
  {
    id: "camp-preset-important-information-6",
    name: "Important information",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Investment Platform"],
    senderPreset: {
      fromName: "Ninety One Investment Platform",
      fromAddress: "ipadvisor@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "galjoen-green",
      subjectLine: "Important information - Subject",
      previewText: "Ninety One Investment Platform",
      heroImageUrl: "",
      headline: "Important information",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "",
    },
  },
  {
    id: "camp-preset-corporate-connect-7",
    name: "Corporate Connect",
    regions: [],
    clientGroups: ["Southern Africa"],
    channels: ["Institutional"],
    senderPreset: {
      fromName: "Ninety One Corporate Solutions",
      fromAddress: "corporateinvestors@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "agulhas-gold",
      subjectLine: "Subject | Corporate Connect - Month Year",
      previewText: "",
      heroImageUrl: "",
      headline: "Corporate Connect",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "",
    },
  },
  {
    id: "camp-preset-us-advisor-monthly-performance-8",
    name: "US Advisor Monthly performance",
    regions: [],
    clientGroups: ["North America"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Ninety One",
      fromAddress: "NinetyOneMarketing@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "springbok-teal",
      subjectLine: "Monthly Performance Update",
      previewText: "Your monthly update on Ninety One's key Global Strategies",
      heroImageUrl: "",
      headline: "Monthly Performance Update",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "Monthly - Offshore Ex ML (3.23.2026)",
    },
  },
  {
    id: "camp-preset-us-advisor-monthly-performance-9",
    name: "US Advisor Monthly performance",
    regions: [],
    clientGroups: ["North America"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Ninety One",
      fromAddress: "NinetyOneMarketing@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "springbok-teal",
      subjectLine: "Monthly Performance Update",
      previewText: "Your monthly update on Ninety One's key Global Strategies",
      heroImageUrl: "",
      headline: "Monthly Performance Update",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "Monthly - Offshore ML Only (3.23.2026)",
    },
  },
  {
    id: "camp-preset-emerging-market-debt-10",
    name: "Emerging Market Debt",
    regions: [],
    clientGroups: ["Europe"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Ninety One",
      fromAddress: "no-reply@ninetyone.com",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "leatherback-yellowood",
      subjectLine: "EM Perspectives - Our latest insights on Emerging Market Deb",
      previewText: "",
      heroImageUrl: "",
      headline: "EM Perspectives",
      subHeadline: "Fixed Income",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "CNE - EM FI Product Segmentation-2026-03-17",
    },
  },
  {
    id: "camp-preset-emerging-market-debt-11",
    name: "Emerging Market Debt",
    regions: [],
    clientGroups: ["United Kingdom"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Prospect's Assigned User",
      fromAddress: "",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "leatherback-yellowood",
      subjectLine: "EM Perspectives - Our latest insights on Emerging Market Deb",
      previewText: "",
      heroImageUrl: "",
      headline: "EM Perspectives",
      subHeadline: "Fixed Income",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "EM FI (Advisor) March 2026",
    },
  },
  {
    id: "camp-preset-emerging-market-debt-12",
    name: "Emerging Market Debt",
    regions: [],
    clientGroups: ["United Kingdom"],
    channels: ["Institutional"],
    senderPreset: {
      fromName: "Prospect's Assigned User",
      fromAddress: "",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "leatherback-yellowood",
      subjectLine: "EM Perspectives - Our latest insights on Emerging Market Deb",
      previewText: "",
      heroImageUrl: "",
      headline: "EM Perspectives",
      subHeadline: "Fixed Income",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "EMD Insti 0226",
    },
  },
  {
    id: "camp-preset-emerging-market-debt-13",
    name: "Emerging Market Debt",
    regions: [],
    clientGroups: ["Europe"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Prospect's Assigned User",
      fromAddress: "",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "leatherback-yellowood",
      subjectLine: "EM Perspectives - Our latest insights on Emerging Market Deb",
      previewText: "",
      heroImageUrl: "",
      headline: "EM Perspectives",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "EMD Insti 0226",
    },
  },
  {
    id: "camp-preset-emerging-market-debt-14",
    name: "Emerging Market Debt",
    regions: [],
    clientGroups: ["Middle East"],
    channels: ["Advisor"],
    senderPreset: {
      fromName: "Prospect's Assigned User",
      fromAddress: "",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "leatherback-yellowood",
      subjectLine: "EM Perspectives - Our latest insights on Emerging Market Deb",
      previewText: "",
      heroImageUrl: "",
      headline: "EM Perspectives",
      subHeadline: "Fixed Income",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "ME EM Fixed Income 0226",
    },
  },
  {
    id: "camp-preset-emerging-market-debt-15",
    name: "Emerging Market Debt",
    regions: [],
    clientGroups: ["Australia"],
    channels: ["Institutional"],
    senderPreset: {
      fromName: "Prospect's Assigned User",
      fromAddress: "",
      replyToEmail: "",
    },
    contentPreset: {
      theme: "leatherback-yellowood",
      subjectLine: "Ninety One EM perspectives - Our latest insights on Emerging",
      previewText: "",
      heroImageUrl: "",
      headline: "EM Perspectives",
      subHeadline: "",
      signatureId: '',
      disclaimerId: '',
      distributionList: '',
      pardotListId: "Australia Institutional \u2013 EM monthly - 0326- report1774825961421",
    },
  },
]