import { useEffect } from 'react'
import type { BriefFormData } from '../../lib/schema'
import { EMAIL_TYPE_LABELS, BRAND_THEMES } from '../../lib/constants'
import type { EmailType } from '../../lib/constants'

interface PrintBriefProps {
  data: BriefFormData
}

export function PrintBrief({ data }: PrintBriefProps) {
  const theme = BRAND_THEMES.find((t) => t.id === data.campaign.theme)

  // Mount into the hidden #print-brief portal
  useEffect(() => {
    const el = document.getElementById('print-brief')
    if (!el) return
    el.innerHTML = ''

    const html = `
      <h1>Ninety One Email Brief</h1>
      <p class="print-meta">Brief ID: ${data.meta.briefId} &nbsp;·&nbsp; Created: ${new Date(data.meta.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} &nbsp;·&nbsp; Status: ${data.meta.status}</p>

      <h2>Campaign</h2>
      <div class="print-grid">
        <div>
          <h3>Email Type</h3><p>${EMAIL_TYPE_LABELS[data.campaign.emailType as EmailType] ?? data.campaign.emailType}</p>
          <h3>Campaign Name</h3><p>${data.campaign.campaignName || '—'}</p>
          <h3>Brand Theme</h3><p>${theme?.label ?? data.campaign.theme}</p>
        </div>
        <div>
          <h3>Subject Line</h3><p>${data.campaign.subjectLine || '—'}</p>
          <h3>Preview Text</h3><p>${data.campaign.previewText || '—'}</p>
          <h3>From</h3><p>${data.campaign.fromName} &lt;${data.campaign.fromAddress}&gt;</p>
        </div>
      </div>

      <h2>Audience</h2>
      <div class="print-grid">
        <div>
          <h3>Client Group</h3><p>${data.audience.clientGroup.map((g) => `<span class="print-badge">${g}</span>`).join('') || '—'}</p>
          <h3>Region</h3><p>${data.audience.region.map((r) => `<span class="print-badge">${r}</span>`).join('') || '—'}</p>
        </div>
        <div>
          <h3>Channel</h3><p>${data.audience.channel.map((c) => `<span class="print-badge">${c}</span>`).join('') || '—'}</p>
          ${data.audience.pardotListId ? `<h3>Pardot List ID</h3><p>${data.audience.pardotListId}</p>` : ''}
        </div>
      </div>

      <h2>Content</h2>
      <h3>Headline</h3><p>${data.content.headline || '—'}</p>
      <h3>Body Intro</h3><p>${data.content.bodyIntro || '—'}</p>
      ${data.content.sections.map((s, i) => `
        <div class="print-section">
          <h3>Section ${i + 1}: ${s.heading}</h3>
          <p>${s.body}</p>
          ${s.imageRequired ? `<p><em>Image required — ${s.imageDescription || 'no description provided'}</em></p>` : ''}
        </div>
      `).join('')}
      <h3>Call to Action</h3>
      <p>${data.content.cta.label} — <a href="${data.content.cta.url}">${data.content.cta.url}</a>${data.content.cta.openInNewTab ? ' (new tab)' : ''}</p>
      ${data.content.legalDisclaimer ? `<h3>Legal Disclaimer</h3><p>${data.content.legalDisclaimer}</p>` : ''}
      <p><em>Unsubscribe link: ${data.content.includeUnsubscribe ? 'Yes' : 'No'}</em></p>

      <h2>Assets</h2>
      <div class="print-grid">
        <div>
          <h3>Logo Variant</h3><p>${data.assets.logoVariant}</p>
          ${data.assets.stripeColour ? `<h3>Stripe Colour</h3><p>${data.assets.stripeColour}</p>` : ''}
        </div>
        <div>
          ${data.assets.heroImageUrl ? `<h3>Hero Image</h3><p>${data.assets.heroImageUrl}</p><p><em>Alt: ${data.assets.heroImageAlt}</em></p>` : ''}
        </div>
      </div>
      ${data.assets.additionalAssetUrls.filter(Boolean).length > 0 ? `<h3>Additional Assets</h3>${data.assets.additionalAssetUrls.filter(Boolean).map((u) => `<p>${u}</p>`).join('')}` : ''}

      <h2>Deadlines</h2>
      <div class="print-grid">
        <div>
          <h3>Content Approval</h3><p>${data.deadlines.contentApprovalDate || '—'}</p>
          <h3>Send Date</h3><p>${data.deadlines.sendDate || '—'}</p>
        </div>
        <div>
          <h3>Urgency</h3><p>${data.deadlines.urgency}</p>
          <h3>1-1 Required</h3><p>${data.deadlines.oneOnOneRequired ? 'Yes' : 'No'}</p>
        </div>
      </div>
      ${data.deadlines.notes ? `<h3>Notes</h3><p>${data.deadlines.notes}</p>` : ''}

      <div class="print-footer">
        <p>Generated by Ninety One Email Briefing Form &nbsp;·&nbsp; ${new Date().toLocaleString('en-GB')}</p>
      </div>
    `
    el.innerHTML = html
  }, [data, theme])

  return null
}
